[package]
name = "kora"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MIT/Apache-2.0"

[dependencies]
crossterm = "0.18.2"
term = "0.6.1"
